version: 2
jobs:
  # test:
  #   docker:
  #     - image: circleci/node:8.9.0
  #   working_directory: ~/repo
  #   steps:
  #     - checkout
  #     # Download and cache dependencies
  #     - restore_cache:
  #         keys:
  #         - v1-dependencies-{{ checksum "package.json" }}
  #         # fallback to using the latest cache if no exact match is found
  #         - v1-dependencies-
  #     - run: npm install
  #     - save_cache:
  #         paths:
  #           - node_modules
  #         key: v1-dependencies-{{ checksum "package.json" }}
  # run tests!
  # - run: npm test
  deployMaster:
    docker:
      - image: circleci/node:8.9.0
    working_directory: ~/repo
    steps:
      - checkout
      # remove node_modules
      - run: rm -rf node_modules
      # install sshpass
      - run:
          name: install sshpass
          command: |
            sudo apt-get install sshpass
      # changing perssion
      - run: chmod +x ./.circleci/deployDev.sh
      # deploy and start server
      - run: ./.circleci/deployDev.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      # - test
      - deployMaster:
          # requires:
          #   - test
          filters:
            branches:
              only: parthDev
